<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Anemoi.Notification.Domain\Anemoi.Notification.Domain.csproj" />
      <ProjectReference Include="..\..\Anemoi.Contract\Anemoi.Contract.Notification\Anemoi.Contract.Notification.csproj" />
      <ProjectReference Include="..\..\Anemoi.Contract\Anemoi.Contract.Hr\Anemoi.Contract.Hr.csproj" />
      <ProjectReference Include="..\..\Anemoi.Contract\Anemoi.Contract.Identity\Anemoi.Contract.Identity.csproj" />
      <ProjectReference Include="..\..\Anemoi.BuildingBlocks\Anemoi.BuildingBlock.Application\Anemoi.BuildingBlock.Application.csproj" />
    </ItemGroup>

</Project>
