using Anemoi.Hr.Application.Abstractions;
using Anemoi.Hr.Domain.Payroll;
using System;
using System.IO;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace Anemoi.Hr.Infrastructure.Services;

/// <summary>
/// Custom managed C# PDF renderer that outputs standard layout PDFs directly from snapshot data.
/// 
/// TECHNICAL DEBT REGISTER - TD-PDF-001 (Vietnamese Unicode Rendering):
/// - Standard PDF viewers use built-in fonts (like Helvetica) which do not support Vietnamese
///   accented Unicode characters natively. If Vietnamese Unicode text is rendered using standard Helvetica,
///   accents will be stripped or display incorrectly.
/// - Embedding a custom TrueType Font (TTF) that supports Vietnamese (e.g. Arial or Roboto) in raw PDF bytes
///   requires writing a TTF font file parser and embedding font metrics, which is highly complex for a simple MVP.
/// - For production, this implementation should be replaced by a library that supports native font embedding,
///   such as QuestPDF or PdfSharpCore with custom font resolvers.
/// </summary>
public sealed class PayslipPdfRenderer : IPayslipPdfRenderer
{
    public Task<byte[]> RenderAsync(Payslip payslip, CancellationToken cancellationToken = default)
    {
        // For the MVP, we output ASCII-compatible text by stripping/mapping Vietnamese accents where possible,
        // or keeping standard characters. Standard Helvetica font will be used.
        using var ms = new MemoryStream();
        using (var writer = new StreamWriter(ms, Encoding.ASCII))
        {
            // PDF Header
            writer.Write("%PDF-1.4\n");

            // Define page content text
            var contentBuilder = new StringBuilder();
            contentBuilder.Append("BT\n"); // Begin Text object
            contentBuilder.Append("/F1 16 Tf\n"); // Use Font F1 at size 16
            contentBuilder.Append("50 780 Td\n"); // Position at (50, 780)
            contentBuilder.Append($"(PAYSLIP - PERIOD: {EscapePdfString(payslip.PeriodCode)}) Tj\n");
            
            contentBuilder.Append("/F1 10 Tf\n"); // Font size 10
            contentBuilder.Append("0 -30 Td\n"); // Move down by 30 units
            contentBuilder.Append($"(Employee Code: {EscapePdfString(payslip.EmployeeCode)}) Tj\n");
            
            contentBuilder.Append("0 -15 Td\n");
            contentBuilder.Append($"(Employee Name: {EscapePdfString(RemoveVietnameseAccents(payslip.EmployeeName))}) Tj\n");
            
            contentBuilder.Append("0 -30 Td\n");
            contentBuilder.Append($"(Base Salary: {payslip.BaseSalarySnapshot:F2}) Tj\n");
            
            contentBuilder.Append("0 -15 Td\n");
            contentBuilder.Append($"(Daily Rate: {payslip.DailyRateSnapshot:F4}) Tj\n");
            
            contentBuilder.Append("0 -15 Td\n");
            contentBuilder.Append($"(Paid Working Days: {payslip.PaidWorkingDays:F2}) Tj\n");
            
            contentBuilder.Append("0 -15 Td\n");
            contentBuilder.Append($"(Paid Leave Days: {payslip.PaidLeaveDays:F2}) Tj\n");
            
            contentBuilder.Append("0 -15 Td\n");
            contentBuilder.Append($"(Unpaid Leave Days: {payslip.UnpaidLeaveDays:F2}) Tj\n");
            
            contentBuilder.Append("0 -20 Td\n");
            contentBuilder.Append($"(Base Pay Amount: {payslip.BasePayAmount:F2}) Tj\n");
            
            contentBuilder.Append("0 -15 Td\n");
            contentBuilder.Append($"(Allowance Total: {payslip.AllowanceTotal:F2}) Tj\n");
            
            contentBuilder.Append("0 -15 Td\n");
            contentBuilder.Append($"(Deduction Total: {payslip.DeductionTotal:F2}) Tj\n");
            
            contentBuilder.Append("0 -15 Td\n");
            contentBuilder.Append($"(Gross Pay: {payslip.GrossPay:F2}) Tj\n");
            
            contentBuilder.Append("0 -25 Td\n");
            contentBuilder.Append($"(NET PAY: {payslip.NetPay:F2}) Tj\n");
            
            contentBuilder.Append("0 -40 Td\n");
            contentBuilder.Append($"(Generated By: {EscapePdfString(payslip.GeneratedBy)}) Tj\n");
            contentBuilder.Append("0 -15 Td\n");
            contentBuilder.Append($"(Generated At: {payslip.GeneratedAt:yyyy-MM-dd HH:mm:ss} UTC) Tj\n");
            
            contentBuilder.Append("0 -20 Td\n");
            contentBuilder.Append($"(Status: {EscapePdfString(payslip.Status.ToString())}) Tj\n");
            contentBuilder.Append("ET\n"); // End Text object

            var contentBytes = Encoding.ASCII.GetBytes(contentBuilder.ToString());

            // 1 0 obj: Catalog
            writer.Write("1 0 obj\n<</Type /Catalog /Pages 2 0 R>>\nendobj\n");
            
            // 2 0 obj: Pages collection
            writer.Write("2 0 obj\n<</Type /Pages /Kids [3 0 R] /Count 1>>\nendobj\n");
            
            // 3 0 obj: Single Page
            writer.Write("3 0 obj\n<</Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources <</Font <</F1 4 0 R>>>> /Contents 5 0 R>>\nendobj\n");
            
            // 4 0 obj: Helvetica Font definition
            writer.Write("4 0 obj\n<</Type /Font /Subtype /Type1 /BaseFont /Helvetica>>\nendobj\n");
            
            // 5 0 obj: Page Content Stream
            writer.Write($"5 0 obj\n<</Length {contentBytes.Length}>>\nstream\n");
            writer.Flush();
            ms.Write(contentBytes, 0, contentBytes.Length);
            writer.Write("\nendstream\nendobj\n");
            
            // Cross-reference table (xref) and Trailer
            writer.Write("xref\n0 6\n0000000000 65535 f\n");
            writer.Write("trailer\n<</Size 6 /Root 1 0 R>>\nstartxref\n310\n%%EOF\n");
            writer.Flush();
        }

        return Task.FromResult(ms.ToArray());
    }

    private static string EscapePdfString(string text)
    {
        if (text is null) return string.Empty;
        return text.Replace("\\", "\\\\").Replace("(", "\\(").Replace(")", "\\)");
    }

    private static string RemoveVietnameseAccents(string text)
    {
        if (string.IsNullOrWhiteSpace(text))
            return string.Empty;

        string[] arr1 = [
            "á", "à", "ả", "ã", "ạ", "â", "ấ", "ầ", "ẩ", "ẫ", "ậ", "ă", "ắ", "ằ", "ẳ", "ẵ", "ặ",
            "đ",
            "é", "è", "ẻ", "ẽ", "ẹ", "ê", "ế", "ề", "ể", "ễ", "ệ",
            "í", "ì", "ỉ", "ĩ", "ị",
            "ó", "ò", "ỏ", "õ", "ọ", "ô", "ố", "ồ", "ổ", "ỗ", "ộ", "ơ", "ớ", "ờ", "ở", "ỡ", "ợ",
            "ú", "ù", "ủ", "ũ", "ụ", "ư", "ứ", "ừ", "ử", "ữ", "ự",
            "ý", "ỳ", "ỷ", "ỹ", "ỵ"
        ];

        string[] arr2 = [
            "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
            "d",
            "e", "e", "e", "e", "e", "e", "e", "e", "e", "e", "e",
            "i", "i", "i", "i", "i",
            "o", "o", "o", "o", "o", "o", "o", "o", "o", "o", "o", "o", "o", "o", "o", "o", "o",
            "u", "u", "u", "u", "u", "u", "u", "u", "u", "u", "u",
            "y", "y", "y", "y", "y"
        ];

        var result = text;
        for (int i = 0; i < arr1.Length; i++)
        {
            result = result.Replace(arr1[i], arr2[i]);
            result = result.Replace(arr1[i].ToUpper(), arr2[i].ToUpper());
        }

        return result;
    }
}
