// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using Anemoi.BuildingBlock.Domain.Abstractions;

namespace Anemoi.BuildingBlock.Domain;

/// <summary>
/// Base class for domain entities with a strongly typed identifier.
/// Entities have identity that persists across their lifecycle.
/// </summary>
/// <typeparam name="TId">The type of the entity's identifier.</typeparam>
public abstract class Entity<TId>
{
    public TId Id { get; set; } = default!;

    private readonly List<IDomainEvent> _domainEvents = [];

    public IReadOnlyCollection<IDomainEvent> DomainEvents => _domainEvents.AsReadOnly();

    public void AddEvent(IDomainEvent @event)
    {
        _domainEvents.Add(@event);
    }

    public void ClearEvents() => _domainEvents.Clear();

    public override bool Equals(object? obj)
    {
        if (obj is not Entity<TId> other) return false;

        if (ReferenceEquals(this, other)) return true;

        if (EqualityComparer<TId>.Default.Equals(Id, default!) || EqualityComparer<TId>.Default.Equals(other.Id, default!)) return false;

        return EqualityComparer<TId>.Default.Equals(Id, other.Id);
    }

    public override int GetHashCode()
    {
        if (EqualityComparer<TId>.Default.Equals(Id, default!)) return base.GetHashCode();

        return Id!.GetHashCode() ^ 1;
    }

    public static bool operator ==(Entity<TId>? a, Entity<TId>? b)
    {
        if (ReferenceEquals(a, null) && ReferenceEquals(b, null)) return true;

        if (a is null) return false;

        // a is guaranteed non-null here due to the check above
        return a!.Equals(b);
    }

    public static bool operator !=(Entity<TId>? a, Entity<TId>? b) => !(a == b);
}
