<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Anemoi.Identity.Domain\Anemoi.Identity.Domain.csproj" />
      <ProjectReference Include="..\..\Anemoi.Contract\Anemoi.Contract.Identity\Anemoi.Contract.Identity.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="HotChocolate.Data" Version="13.9.16" />
      <PackageReference Include="Riok.Mapperly" Version="4.3.1" />
    </ItemGroup>

</Project>
