<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <Compile Remove="ModelIds\**\*.cs" />
        <ProjectReference Include="..\Anemoi.Contract.MasterData.ModelIds\Anemoi.Contract.MasterData.ModelIds.csproj"/>
        <ProjectReference Include="..\Anemoi.Contract.CrossCuttingConcern\Anemoi.Contract.CrossCuttingConcern.csproj"/>

    </ItemGroup>
    
</Project>
