<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Anemoi.Contract\Anemoi.Contract.MasterData.ModelIds\Anemoi.Contract.MasterData.ModelIds.csproj" />
    </ItemGroup>
    

</Project>
