using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Anemoi.Hr.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class ConsolidateLeavePolicies : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Phase 0: Seed required LeaveTypes before any data migration
            // The LeaveTypes table may be empty (seed data runs after migrations),
            // so inserting here ensures Phase 1a and Phase 3 can resolve them.
            migrationBuilder.Sql(@"
                INSERT INTO ""LeaveTypes"" (""Id"", ""Code"", ""Name"", ""IsPaid"",
                    ""RequiresApproval"", ""AnnualEntitlement"", ""CarryForwardAllowed"",
                    ""MaxCarryForwardDays"", ""IsActive"", ""CreatedAt"", ""UpdatedAt"")
                VALUES ('50000000-0000-0000-0000-000000000001',
                    'Annual', 'Annual Leave',
                    TRUE, TRUE, 15, TRUE, 5, TRUE, NOW(), NOW())
                ON CONFLICT (""Code"") DO NOTHING;
            ");

            // Phase 1: Data copy — old column names still exist (before any schema changes)
            // 1a. Copy MasterDataLeavePolicies rows into old LeavePolicies schema
            migrationBuilder.Sql(@"
                INSERT INTO ""LeavePolicies"" (""Id"", ""Code"", ""Name"", ""LeaveTypeCode"",
                    ""MonthlyAccrualDays"", ""AnnualMaxDays"", ""AllowCarryForward"",
                    ""MaxCarryForwardDays"", ""IsActive"", ""CreatedAt"", ""UpdatedAt"")
                SELECT m.""Id"", m.""Code"", m.""Name"", lt.""Code"",
                    m.""AnnualEntitlement"" / 12, m.""AnnualEntitlement"",
                    lt.""CarryForwardAllowed"", lt.""MaxCarryForwardDays"",
                    m.""IsActive"", m.""CreatedAt"", m.""UpdatedAt""
                FROM ""MasterDataLeavePolicies"" m
                JOIN ""LeaveTypes"" lt ON lt.""Id"" = m.""LeaveTypeId""
                ON CONFLICT (""Id"") DO NOTHING;
            ");

            // 1b. Fix MonthlyAccrualDays → set to AnnualMaxDays (since MonthlyAccrualDays
            //     will be RENAMED to AnnualEntitlement, not dropped)
            migrationBuilder.Sql(@"
                UPDATE ""LeavePolicies"" SET ""MonthlyAccrualDays"" = ""AnnualMaxDays""
                WHERE ""AnnualMaxDays"" > 0;
            ");

            // Phase 2: Schema changes (auto-generated by EF)
            migrationBuilder.DropTable(
                name: "MasterDataLeavePolicies");

            migrationBuilder.DropColumn(
                name: "AllowCarryForward",
                table: "LeavePolicies");

            migrationBuilder.DropColumn(
                name: "AnnualMaxDays",
                table: "LeavePolicies");

            migrationBuilder.DropColumn(
                name: "MaxCarryForwardDays",
                table: "LeavePolicies");

            migrationBuilder.RenameColumn(
                name: "MonthlyAccrualDays",
                table: "LeavePolicies",
                newName: "AnnualEntitlement");

            migrationBuilder.RenameColumn(
                name: "LeaveTypeCode",
                table: "LeavePolicies",
                newName: "ApplicableGradeCode");

            migrationBuilder.AddColumn<Guid>(
                name: "LeaveTypeId",
                table: "LeavePolicies",
                type: "uuid",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.AddColumn<uint>(
                name: "xmin",
                table: "LeavePolicies",
                type: "xid",
                rowVersion: true,
                nullable: false,
                defaultValue: 0u);

            // Phase 3: Set LeaveTypeId using renamed columns, then clear ApplicableGradeCode
            // (which held the old LeaveTypeCode value) since we want it empty for all grades
            // This runs BEFORE FK constraint is added so we have valid LeaveTypeIds first
            migrationBuilder.Sql(@"
                UPDATE ""LeavePolicies"" lp
                SET
                    ""LeaveTypeId"" = lt.""Id"",
                    ""ApplicableGradeCode"" = ''''
                FROM ""LeaveTypes"" lt
                WHERE lt.""Code"" = lp.""ApplicableGradeCode"";
            ");

            // Phase 3.5: Safety net — assign any rows that couldn't be matched to
            // a LeaveType (e.g., old rows with a LeaveTypeCode that doesn't match
            // any LeaveTypes.Code) to the default Annual leave type. This preserves
            // related data (LeaveBalances, LeaveRequests, etc.) and satisfies the FK.
            // This runs BEFORE FK constraint so we don't violate referential integrity.
            migrationBuilder.Sql(@"
                UPDATE ""LeavePolicies""
                SET ""LeaveTypeId"" = '50000000-0000-0000-0000-000000000001',
                    ""ApplicableGradeCode"" = ''''
                WHERE ""LeaveTypeId"" = '00000000-0000-0000-0000-000000000000';
            ");

            // Phase 4: Indexes and FK constraints (after data is clean)
            migrationBuilder.CreateIndex(
                name: "IX_LeavePolicies_LeaveTypeId_ApplicableGradeCode",
                table: "LeavePolicies",
                columns: new[] { "LeaveTypeId", "ApplicableGradeCode" },
                unique: true);

            migrationBuilder.AddForeignKey(
                name: "FK_LeavePolicies_LeaveTypes_LeaveTypeId",
                table: "LeavePolicies",
                column: "LeaveTypeId",
                principalTable: "LeaveTypes",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_LeavePolicies_LeaveTypes_LeaveTypeId",
                table: "LeavePolicies");

            migrationBuilder.DropIndex(
                name: "IX_LeavePolicies_LeaveTypeId_ApplicableGradeCode",
                table: "LeavePolicies");

            migrationBuilder.DropColumn(
                name: "LeaveTypeId",
                table: "LeavePolicies");

            migrationBuilder.DropColumn(
                name: "xmin",
                table: "LeavePolicies");

            migrationBuilder.RenameColumn(
                name: "ApplicableGradeCode",
                table: "LeavePolicies",
                newName: "LeaveTypeCode");

            migrationBuilder.RenameColumn(
                name: "AnnualEntitlement",
                table: "LeavePolicies",
                newName: "MonthlyAccrualDays");

            migrationBuilder.AddColumn<bool>(
                name: "AllowCarryForward",
                table: "LeavePolicies",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<decimal>(
                name: "AnnualMaxDays",
                table: "LeavePolicies",
                type: "numeric(9,2)",
                precision: 9,
                scale: 2,
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<decimal>(
                name: "MaxCarryForwardDays",
                table: "LeavePolicies",
                type: "numeric(9,2)",
                precision: 9,
                scale: 2,
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.CreateTable(
                name: "MasterDataLeavePolicies",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    LeaveTypeId = table.Column<Guid>(type: "uuid", nullable: false),
                    AnnualEntitlement = table.Column<decimal>(type: "numeric(9,2)", precision: 9, scale: 2, nullable: false),
                    ApplicableGradeCode = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    Code = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    IsActive = table.Column<bool>(type: "boolean", nullable: false),
                    Name = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    xmin = table.Column<uint>(type: "xid", rowVersion: true, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_MasterDataLeavePolicies", x => x.Id);
                    table.ForeignKey(
                        name: "FK_MasterDataLeavePolicies_LeaveTypes_LeaveTypeId",
                        column: x => x.LeaveTypeId,
                        principalTable: "LeaveTypes",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_MasterDataLeavePolicies_Code",
                table: "MasterDataLeavePolicies",
                column: "Code",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_MasterDataLeavePolicies_LeaveTypeId_ApplicableGradeCode",
                table: "MasterDataLeavePolicies",
                columns: new[] { "LeaveTypeId", "ApplicableGradeCode" },
                unique: true);
        }
    }
}
