// <auto-generated />
using System;
using Anemoi.Hr.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Anemoi.Hr.Infrastructure.Migrations
{
    [DbContext(typeof(HrDbContext))]
    [Migration("20260605093152_AddLeaveBalanceConcurrencyToken")]
    partial class AddLeaveBalanceConcurrencyToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Anemoi.Hr.Domain.Departments.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DepartmentTypeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ManagerEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ParentDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ManagerEmployeeId");

                    b.HasIndex("ParentDepartmentId");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Employees.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<Guid?>("DirectManagerEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("EmploymentStatusCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("EmploymentTypeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("IdentityUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("JoinDate")
                        .HasColumnType("date");

                    b.Property<string>("PersonalEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("PrimaryDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PrimaryPositionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("DirectManagerEmployeeId");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.HasIndex("IdentityUserId")
                        .IsUnique();

                    b.HasIndex("PrimaryDepartmentId");

                    b.HasIndex("PrimaryPositionId");

                    b.HasIndex("WorkEmail")
                        .IsUnique();

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Employees.EmployeeDepartmentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeId", "EffectiveFrom");

                    b.ToTable("EmployeeDepartmentHistories", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Employees.EmployeeGradeHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("GradeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "EffectiveFrom");

                    b.ToTable("EmployeeGradeHistories", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Employees.EmployeeIdentityLinkLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdentityUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("MatchStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("WorkEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("IdentityUserId");

                    b.HasIndex("MatchStatus");

                    b.ToTable("EmployeeIdentityLinkLogs", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Employees.EmployeeManagerHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ManagerEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerEmployeeId");

                    b.HasIndex("EmployeeId", "EffectiveFrom");

                    b.ToTable("EmployeeManagerHistories", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Employees.EmployeePositionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.HasIndex("EmployeeId", "EffectiveFrom");

                    b.ToTable("EmployeePositionHistories", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Leaves.LeaveAccrualRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AccruedDays")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LeavePolicyId")
                        .HasColumnType("uuid");

                    b.Property<string>("YearMonth")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.HasKey("Id");

                    b.HasIndex("LeavePolicyId");

                    b.HasIndex("EmployeeId", "LeavePolicyId", "YearMonth")
                        .IsUnique();

                    b.ToTable("LeaveAccrualRuns", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Leaves.LeaveBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AccruedDays")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<decimal>("AdjustedDays")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LeavePolicyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("OpeningDays")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<decimal>("PendingDays")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<decimal>("RemainingDays")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UsedDays")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("LeavePolicyId");

                    b.HasIndex("EmployeeId", "LeavePolicyId", "Year")
                        .IsUnique();

                    b.ToTable("LeaveBalances", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Leaves.LeavePolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowCarryForward")
                        .HasColumnType("boolean");

                    b.Property<decimal>("AnnualMaxDays")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LeaveTypeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("MaxCarryForwardDays")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<decimal>("MonthlyAccrualDays")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LeavePolicies", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Leaves.LeaveRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApproverEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("LeavePolicyId")
                        .HasColumnType("uuid");

                    b.Property<string>("LeaveTypeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Reason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<decimal>("RequestedDays")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApproverEmployeeId");

                    b.HasIndex("LeavePolicyId");

                    b.HasIndex("EmployeeId", "StatusCode");

                    b.HasIndex("StartDate", "EndDate");

                    b.ToTable("LeaveRequests", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Leaves.LeaveTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("BalanceAfterDays")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Days")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LeaveBalanceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LeavePolicyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LeaveRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("SourceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourceType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TransactionTypeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("LeaveBalanceId");

                    b.HasIndex("LeavePolicyId");

                    b.HasIndex("LeaveRequestId");

                    b.HasIndex("EmployeeId", "CreatedAt");

                    b.ToTable("LeaveTransactions", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Positions.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PositionTypeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.ToTable("Positions", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Departments.Department", b =>
                {
                    b.HasOne("Anemoi.Hr.Domain.Employees.Employee", "ManagerEmployee")
                        .WithMany()
                        .HasForeignKey("ManagerEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Anemoi.Hr.Domain.Departments.Department", "ParentDepartment")
                        .WithMany("ChildDepartments")
                        .HasForeignKey("ParentDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ManagerEmployee");

                    b.Navigation("ParentDepartment");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Employees.Employee", b =>
                {
                    b.HasOne("Anemoi.Hr.Domain.Employees.Employee", "DirectManager")
                        .WithMany("DirectReports")
                        .HasForeignKey("DirectManagerEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Anemoi.Hr.Domain.Departments.Department", "PrimaryDepartment")
                        .WithMany("PrimaryEmployees")
                        .HasForeignKey("PrimaryDepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Anemoi.Hr.Domain.Positions.Position", "PrimaryPosition")
                        .WithMany("PrimaryEmployees")
                        .HasForeignKey("PrimaryPositionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DirectManager");

                    b.Navigation("PrimaryDepartment");

                    b.Navigation("PrimaryPosition");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Employees.EmployeeDepartmentHistory", b =>
                {
                    b.HasOne("Anemoi.Hr.Domain.Departments.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Anemoi.Hr.Domain.Employees.Employee", "Employee")
                        .WithMany("DepartmentHistories")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Department");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Employees.EmployeeGradeHistory", b =>
                {
                    b.HasOne("Anemoi.Hr.Domain.Employees.Employee", "Employee")
                        .WithMany("GradeHistories")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Employees.EmployeeIdentityLinkLog", b =>
                {
                    b.HasOne("Anemoi.Hr.Domain.Employees.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Employees.EmployeeManagerHistory", b =>
                {
                    b.HasOne("Anemoi.Hr.Domain.Employees.Employee", "Employee")
                        .WithMany("ManagerHistories")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Anemoi.Hr.Domain.Employees.Employee", "ManagerEmployee")
                        .WithMany()
                        .HasForeignKey("ManagerEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");

                    b.Navigation("ManagerEmployee");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Employees.EmployeePositionHistory", b =>
                {
                    b.HasOne("Anemoi.Hr.Domain.Employees.Employee", "Employee")
                        .WithMany("PositionHistories")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Anemoi.Hr.Domain.Positions.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Leaves.LeaveAccrualRun", b =>
                {
                    b.HasOne("Anemoi.Hr.Domain.Employees.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Anemoi.Hr.Domain.Leaves.LeavePolicy", "LeavePolicy")
                        .WithMany("LeaveAccrualRuns")
                        .HasForeignKey("LeavePolicyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");

                    b.Navigation("LeavePolicy");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Leaves.LeaveBalance", b =>
                {
                    b.HasOne("Anemoi.Hr.Domain.Employees.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Anemoi.Hr.Domain.Leaves.LeavePolicy", "LeavePolicy")
                        .WithMany("LeaveBalances")
                        .HasForeignKey("LeavePolicyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");

                    b.Navigation("LeavePolicy");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Leaves.LeaveRequest", b =>
                {
                    b.HasOne("Anemoi.Hr.Domain.Employees.Employee", "ApproverEmployee")
                        .WithMany()
                        .HasForeignKey("ApproverEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Anemoi.Hr.Domain.Employees.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Anemoi.Hr.Domain.Leaves.LeavePolicy", "LeavePolicy")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("LeavePolicyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApproverEmployee");

                    b.Navigation("Employee");

                    b.Navigation("LeavePolicy");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Leaves.LeaveTransaction", b =>
                {
                    b.HasOne("Anemoi.Hr.Domain.Employees.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Anemoi.Hr.Domain.Leaves.LeaveBalance", "LeaveBalance")
                        .WithMany("LeaveTransactions")
                        .HasForeignKey("LeaveBalanceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Anemoi.Hr.Domain.Leaves.LeavePolicy", "LeavePolicy")
                        .WithMany("LeaveTransactions")
                        .HasForeignKey("LeavePolicyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Anemoi.Hr.Domain.Leaves.LeaveRequest", "LeaveRequest")
                        .WithMany("LeaveTransactions")
                        .HasForeignKey("LeaveRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");

                    b.Navigation("LeaveBalance");

                    b.Navigation("LeavePolicy");

                    b.Navigation("LeaveRequest");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Positions.Position", b =>
                {
                    b.HasOne("Anemoi.Hr.Domain.Departments.Department", "Department")
                        .WithMany("Positions")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Departments.Department", b =>
                {
                    b.Navigation("ChildDepartments");

                    b.Navigation("Positions");

                    b.Navigation("PrimaryEmployees");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Employees.Employee", b =>
                {
                    b.Navigation("DepartmentHistories");

                    b.Navigation("DirectReports");

                    b.Navigation("GradeHistories");

                    b.Navigation("ManagerHistories");

                    b.Navigation("PositionHistories");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Leaves.LeaveBalance", b =>
                {
                    b.Navigation("LeaveTransactions");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Leaves.LeavePolicy", b =>
                {
                    b.Navigation("LeaveAccrualRuns");

                    b.Navigation("LeaveBalances");

                    b.Navigation("LeaveRequests");

                    b.Navigation("LeaveTransactions");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Leaves.LeaveRequest", b =>
                {
                    b.Navigation("LeaveTransactions");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Positions.Position", b =>
                {
                    b.Navigation("PrimaryEmployees");
                });
#pragma warning restore 612, 618
        }
    }
}
