// <auto-generated />
using System;
using Anemoi.Hr.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Anemoi.Hr.Infrastructure.Migrations
{
    [DbContext(typeof(HrDbContext))]
    [Migration("20260606055926_UpdatePayrollDailyRatePrecision")]
    partial class UpdatePayrollDailyRatePrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Anemoi.Hr.Domain.Compensation.AllowanceType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTaxable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AllowanceTypes", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Compensation.EmployeeAllowance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AllowanceTypeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AllowanceTypeId");

                    b.HasIndex("EmployeeId", "AllowanceTypeId", "Currency")
                        .IsUnique()
                        .HasFilter("\"EffectiveTo\" IS NULL");

                    b.HasIndex("EmployeeId", "AllowanceTypeId", "Currency", "EffectiveFrom")
                        .IsUnique();

                    b.ToTable("EmployeeAllowances", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Compensation.EmployeeSalary", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("GradeCodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SalaryGradeId")
                        .HasColumnType("uuid");

                    b.Property<int>("SalaryType")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasFilter("\"EffectiveTo\" IS NULL");

                    b.HasIndex("SalaryGradeId");

                    b.HasIndex("EmployeeId", "EffectiveFrom")
                        .IsUnique();

                    b.ToTable("EmployeeSalaries", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Compensation.PositionAllowance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AllowanceTypeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AllowanceTypeId");

                    b.HasIndex("PositionId", "AllowanceTypeId")
                        .IsUnique();

                    b.ToTable("PositionAllowances", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Compensation.SalaryGrade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("GradeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("GradeCode")
                        .IsUnique();

                    b.ToTable("SalaryGrades", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Compensation.SalaryRange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MaxSalary")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinSalary")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("SalaryGradeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("SalaryGradeId");

                    b.ToTable("SalaryRanges", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Compensation.SalaryValidationBypassLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BypassReason")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("GradeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("RequestedSalary")
                        .HasColumnType("numeric");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("SalaryValidationBypassLogs", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Contracts.EmployeeContract", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AttachmentFileId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ContractTypeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid?>("PreviousContractId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("SignedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ContractNumber")
                        .IsUnique();

                    b.HasIndex("EmployeeId", "StatusCode");

                    b.HasIndex("StatusCode", "EndDate");

                    b.HasIndex("EmployeeId", "StartDate", "EndDate");

                    b.ToTable("EmployeeContracts", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Departments.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DepartmentTypeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ManagerEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ParentDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ManagerEmployeeId");

                    b.HasIndex("ParentDepartmentId");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Employees.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<Guid?>("DirectManagerEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("EmploymentStatusCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("EmploymentTypeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("GradeCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("IdentityUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("JoinDate")
                        .HasColumnType("date");

                    b.Property<string>("PersonalEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("PrimaryDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PrimaryPositionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("DirectManagerEmployeeId");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.HasIndex("IdentityUserId")
                        .IsUnique();

                    b.HasIndex("PrimaryDepartmentId");

                    b.HasIndex("PrimaryPositionId");

                    b.HasIndex("WorkEmail")
                        .IsUnique();

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Employees.EmployeeDepartmentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OldDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("OldDepartmentId");

                    b.HasIndex("EmployeeId", "EffectiveFrom")
                        .IsUnique();

                    b.ToTable("EmployeeDepartmentHistories", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Employees.EmployeeGradeHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("GradeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("OldGradeCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "EffectiveFrom")
                        .IsUnique();

                    b.ToTable("EmployeeGradeHistories", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Employees.EmployeeIdentityLinkLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdentityUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDryRun")
                        .HasColumnType("boolean");

                    b.Property<string>("MatchStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("WorkEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("IdentityUserId");

                    b.HasIndex("IsDryRun");

                    b.HasIndex("MatchStatus");

                    b.ToTable("EmployeeIdentityLinkLogs", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Employees.EmployeeManagerHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ManagerEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerEmployeeId");

                    b.HasIndex("EmployeeId", "EffectiveFrom");

                    b.ToTable("EmployeeManagerHistories", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Employees.EmployeePositionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OldPositionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("OldPositionId");

                    b.HasIndex("PositionId");

                    b.HasIndex("EmployeeId", "EffectiveFrom")
                        .IsUnique();

                    b.ToTable("EmployeePositionHistories", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Leaves.LeaveAccrualRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AccruedDays")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LeavePolicyId")
                        .HasColumnType("uuid");

                    b.Property<string>("YearMonth")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.HasKey("Id");

                    b.HasIndex("LeavePolicyId");

                    b.HasIndex("EmployeeId", "LeavePolicyId", "YearMonth")
                        .IsUnique();

                    b.ToTable("LeaveAccrualRuns", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Leaves.LeaveBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AccruedDays")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<decimal>("AdjustedDays")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LeavePolicyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("OpeningDays")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<decimal>("PendingDays")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<decimal>("RemainingDays")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UsedDays")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("LeavePolicyId");

                    b.HasIndex("EmployeeId", "LeavePolicyId", "Year")
                        .IsUnique();

                    b.ToTable("LeaveBalances", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Leaves.LeavePolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowCarryForward")
                        .HasColumnType("boolean");

                    b.Property<decimal>("AnnualMaxDays")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LeaveTypeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("MaxCarryForwardDays")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<decimal>("MonthlyAccrualDays")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LeavePolicies", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Leaves.LeaveRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApproverEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("LeavePolicyId")
                        .HasColumnType("uuid");

                    b.Property<string>("LeaveTypeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Reason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<decimal>("RequestedDays")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApproverEmployeeId");

                    b.HasIndex("LeavePolicyId");

                    b.HasIndex("EmployeeId", "StatusCode");

                    b.HasIndex("StartDate", "EndDate");

                    b.HasIndex("StatusCode", "StartDate", "EndDate");

                    b.ToTable("LeaveRequests", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Leaves.LeaveTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("BalanceAfterDays")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Days")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LeaveBalanceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LeavePolicyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LeaveRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("SourceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourceType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TransactionTypeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("LeaveBalanceId");

                    b.HasIndex("LeavePolicyId");

                    b.HasIndex("LeaveRequestId");

                    b.HasIndex("EmployeeId", "CreatedAt");

                    b.ToTable("LeaveTransactions", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Payroll.PayrollItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ItemTypeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("PayrollRunId")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("PayrollRunId");

                    b.ToTable("PayrollItems", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Payroll.PayrollPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("PeriodCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("StandardWorkingDays")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("PeriodCode")
                        .IsUnique();

                    b.ToTable("PayrollPeriods", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Payroll.PayrollRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("BasePayAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("BaseSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CalculatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal>("DailyRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("GrossAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("NetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PaidWorkingDays")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<string>("PayScheduleType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("PayrollPeriodId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("StandardWorkingDays")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<decimal>("TotalAllowanceAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalDeductionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("UnpaidLeaveDays")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PayrollPeriodId", "EmployeeId")
                        .IsUnique();

                    b.ToTable("PayrollRuns", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Positions.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PositionTypeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.ToTable("Positions", (string)null);
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Compensation.EmployeeAllowance", b =>
                {
                    b.HasOne("Anemoi.Hr.Domain.Compensation.AllowanceType", "AllowanceType")
                        .WithMany()
                        .HasForeignKey("AllowanceTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Anemoi.Hr.Domain.Employees.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AllowanceType");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Compensation.EmployeeSalary", b =>
                {
                    b.HasOne("Anemoi.Hr.Domain.Employees.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Anemoi.Hr.Domain.Compensation.SalaryGrade", "SalaryGrade")
                        .WithMany()
                        .HasForeignKey("SalaryGradeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");

                    b.Navigation("SalaryGrade");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Compensation.PositionAllowance", b =>
                {
                    b.HasOne("Anemoi.Hr.Domain.Compensation.AllowanceType", "AllowanceType")
                        .WithMany()
                        .HasForeignKey("AllowanceTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Anemoi.Hr.Domain.Positions.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AllowanceType");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Compensation.SalaryRange", b =>
                {
                    b.HasOne("Anemoi.Hr.Domain.Compensation.SalaryGrade", "SalaryGrade")
                        .WithMany("Ranges")
                        .HasForeignKey("SalaryGradeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("SalaryGrade");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Contracts.EmployeeContract", b =>
                {
                    b.HasOne("Anemoi.Hr.Domain.Employees.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Anemoi.Hr.Domain.Contracts.ContractTerminationDetail", "TerminationDetail", b1 =>
                        {
                            b1.Property<Guid>("EmployeeContractId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Notes")
                                .HasMaxLength(1024)
                                .HasColumnType("character varying(1024)")
                                .HasColumnName("TerminationNotes");

                            b1.Property<string>("ReasonCode")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("TerminationReasonCode");

                            b1.Property<DateOnly>("TerminatedDate")
                                .HasColumnType("date")
                                .HasColumnName("TerminatedDate");

                            b1.Property<string>("TerminationAttachmentId")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("TerminationAttachmentId");

                            b1.HasKey("EmployeeContractId");

                            b1.ToTable("EmployeeContracts");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeContractId");
                        });

                    b.Navigation("Employee");

                    b.Navigation("TerminationDetail");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Departments.Department", b =>
                {
                    b.HasOne("Anemoi.Hr.Domain.Employees.Employee", "ManagerEmployee")
                        .WithMany()
                        .HasForeignKey("ManagerEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Anemoi.Hr.Domain.Departments.Department", "ParentDepartment")
                        .WithMany("ChildDepartments")
                        .HasForeignKey("ParentDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ManagerEmployee");

                    b.Navigation("ParentDepartment");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Employees.Employee", b =>
                {
                    b.HasOne("Anemoi.Hr.Domain.Employees.Employee", "DirectManager")
                        .WithMany("DirectReports")
                        .HasForeignKey("DirectManagerEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Anemoi.Hr.Domain.Departments.Department", "PrimaryDepartment")
                        .WithMany("PrimaryEmployees")
                        .HasForeignKey("PrimaryDepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Anemoi.Hr.Domain.Positions.Position", "PrimaryPosition")
                        .WithMany("PrimaryEmployees")
                        .HasForeignKey("PrimaryPositionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DirectManager");

                    b.Navigation("PrimaryDepartment");

                    b.Navigation("PrimaryPosition");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Employees.EmployeeDepartmentHistory", b =>
                {
                    b.HasOne("Anemoi.Hr.Domain.Departments.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Anemoi.Hr.Domain.Employees.Employee", "Employee")
                        .WithMany("DepartmentHistories")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Anemoi.Hr.Domain.Departments.Department", "OldDepartment")
                        .WithMany()
                        .HasForeignKey("OldDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Employee");

                    b.Navigation("OldDepartment");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Employees.EmployeeGradeHistory", b =>
                {
                    b.HasOne("Anemoi.Hr.Domain.Employees.Employee", "Employee")
                        .WithMany("GradeHistories")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Employees.EmployeeIdentityLinkLog", b =>
                {
                    b.HasOne("Anemoi.Hr.Domain.Employees.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Employees.EmployeeManagerHistory", b =>
                {
                    b.HasOne("Anemoi.Hr.Domain.Employees.Employee", "Employee")
                        .WithMany("ManagerHistories")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Anemoi.Hr.Domain.Employees.Employee", "ManagerEmployee")
                        .WithMany()
                        .HasForeignKey("ManagerEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");

                    b.Navigation("ManagerEmployee");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Employees.EmployeePositionHistory", b =>
                {
                    b.HasOne("Anemoi.Hr.Domain.Employees.Employee", "Employee")
                        .WithMany("PositionHistories")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Anemoi.Hr.Domain.Positions.Position", "OldPosition")
                        .WithMany()
                        .HasForeignKey("OldPositionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Anemoi.Hr.Domain.Positions.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");

                    b.Navigation("OldPosition");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Leaves.LeaveAccrualRun", b =>
                {
                    b.HasOne("Anemoi.Hr.Domain.Employees.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Anemoi.Hr.Domain.Leaves.LeavePolicy", "LeavePolicy")
                        .WithMany("LeaveAccrualRuns")
                        .HasForeignKey("LeavePolicyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");

                    b.Navigation("LeavePolicy");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Leaves.LeaveBalance", b =>
                {
                    b.HasOne("Anemoi.Hr.Domain.Employees.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Anemoi.Hr.Domain.Leaves.LeavePolicy", "LeavePolicy")
                        .WithMany("LeaveBalances")
                        .HasForeignKey("LeavePolicyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");

                    b.Navigation("LeavePolicy");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Leaves.LeaveRequest", b =>
                {
                    b.HasOne("Anemoi.Hr.Domain.Employees.Employee", "ApproverEmployee")
                        .WithMany()
                        .HasForeignKey("ApproverEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Anemoi.Hr.Domain.Employees.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Anemoi.Hr.Domain.Leaves.LeavePolicy", "LeavePolicy")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("LeavePolicyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApproverEmployee");

                    b.Navigation("Employee");

                    b.Navigation("LeavePolicy");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Leaves.LeaveTransaction", b =>
                {
                    b.HasOne("Anemoi.Hr.Domain.Employees.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Anemoi.Hr.Domain.Leaves.LeaveBalance", "LeaveBalance")
                        .WithMany("LeaveTransactions")
                        .HasForeignKey("LeaveBalanceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Anemoi.Hr.Domain.Leaves.LeavePolicy", "LeavePolicy")
                        .WithMany("LeaveTransactions")
                        .HasForeignKey("LeavePolicyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Anemoi.Hr.Domain.Leaves.LeaveRequest", "LeaveRequest")
                        .WithMany("LeaveTransactions")
                        .HasForeignKey("LeaveRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");

                    b.Navigation("LeaveBalance");

                    b.Navigation("LeavePolicy");

                    b.Navigation("LeaveRequest");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Payroll.PayrollItem", b =>
                {
                    b.HasOne("Anemoi.Hr.Domain.Payroll.PayrollRun", "PayrollRun")
                        .WithMany("PayrollItems")
                        .HasForeignKey("PayrollRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PayrollRun");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Payroll.PayrollRun", b =>
                {
                    b.HasOne("Anemoi.Hr.Domain.Employees.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Anemoi.Hr.Domain.Payroll.PayrollPeriod", "PayrollPeriod")
                        .WithMany()
                        .HasForeignKey("PayrollPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PayrollPeriod");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Positions.Position", b =>
                {
                    b.HasOne("Anemoi.Hr.Domain.Departments.Department", "Department")
                        .WithMany("Positions")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Compensation.SalaryGrade", b =>
                {
                    b.Navigation("Ranges");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Departments.Department", b =>
                {
                    b.Navigation("ChildDepartments");

                    b.Navigation("Positions");

                    b.Navigation("PrimaryEmployees");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Employees.Employee", b =>
                {
                    b.Navigation("DepartmentHistories");

                    b.Navigation("DirectReports");

                    b.Navigation("GradeHistories");

                    b.Navigation("ManagerHistories");

                    b.Navigation("PositionHistories");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Leaves.LeaveBalance", b =>
                {
                    b.Navigation("LeaveTransactions");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Leaves.LeavePolicy", b =>
                {
                    b.Navigation("LeaveAccrualRuns");

                    b.Navigation("LeaveBalances");

                    b.Navigation("LeaveRequests");

                    b.Navigation("LeaveTransactions");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Leaves.LeaveRequest", b =>
                {
                    b.Navigation("LeaveTransactions");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Payroll.PayrollRun", b =>
                {
                    b.Navigation("PayrollItems");
                });

            modelBuilder.Entity("Anemoi.Hr.Domain.Positions.Position", b =>
                {
                    b.Navigation("PrimaryEmployees");
                });
#pragma warning restore 612, 618
        }
    }
}
