<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>annotations</Nullable>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Anemoi.Hr.Domain\Anemoi.Hr.Domain.csproj" />
        <ProjectReference Include="..\..\Anemoi.BuildingBlocks\Anemoi.BuildingBlock.Application\Anemoi.BuildingBlock.Application.csproj" />
        <ProjectReference Include="..\..\Anemoi.Contract\Anemoi.Contract.Identity\Anemoi.Contract.Identity.csproj" />
        <ProjectReference Include="..\..\Anemoi.Contract\Anemoi.Contract.MasterData\Anemoi.Contract.MasterData.csproj" />
        <ProjectReference Include="..\..\Anemoi.Contract\Anemoi.Contract.Hr\Anemoi.Contract.Hr.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Npgsql" Version="10.0.0" />
        <PackageReference Include="Riok.Mapperly" Version="4.3.1" />
    </ItemGroup>

</Project>
